defaults:
  - _self_
  - config.yaml

# @package _global_

mqtt:
  _target_: ctrlsolar.io.Mqtt
  host: ???
  port: ???
  username: ${oc.env:MQTT_USERNAME}
  password: ${oc.env:MQTT_PASSWORD}

loop:
  _target_: ctrlsolar.loop.Loop
  update_interval: ???
  controllers: 
    - _target_: ctrlsolar.controller.ReduceConsumption
      max_power_W: ???
      min_power_W: ???
      control_threshold_W: ???
      offset_W: ???   
      inverter:
        _target_: ctrlsolar.inverter.DeyeSunM160G4.initialize_from_deye2mqtt
        topic: ???
      meter: 
        _target_: ctrlsolar.io.MqttSensor
        topic: ???

    - _target_: ctrlsolar.controller.ProductionForecast
      forecast:
        _target_: ctrlsolar.panels.forecast.OpenMeteoForecast
        latitude: 42.46903090913205
        longitude: -71.35063628495487
        timezone: America/New_York
      panels:
        - _target_: ctrlsolar.panels.GenericPanel
          tilt: 45
          azimuth: 180
          area: 1.9981
          efficiency: 0.22       
        - _target_: ctrlsolar.panels.GenericPanel
          tilt: 45
          azimuth: 180
          area: 1.9981
          efficiency: 0.22           
      energy_today: 
        _target_: ctrlsolar.io.MqttSensor
        topic: ???