services:
  ctrl-solar:
    container_name: ctrl-solar
    image: ghcr.io/st0nedb/ctrl-solar:latest
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    env_file: .env
    command: ["python", "-m", "ctrlsolar.app", "--config-file", "/app/config.yaml"]
