mqtt:
  host: localhost
  port: 1883
  username:
  password:

site:
  latitude: 42.46903090913205
  longitude: -71.35063628495487
  timezone: America/New_York

batteries:
  - type: noah2000
    serial: BATTERY1
    panels:
      - tilt: 45
        azimuth: 180
        area: 1.9981
        efficiency: 0.22
      - tilt: 45
        azimuth: 180
        area: 1.9981
        efficiency: 0.22
      - tilt: 45
        azimuth: 180
        area: 1.9981
        efficiency: 0.22
      - tilt: 45
        azimuth: 180
        area: 1.9981
        efficiency: 0.22
    stack_count: 2
    use_smoothing: true

powermeter:
  type: mqtt_sensor
  topic: tele/tasmota_799C3C/SENSOR
  filter:
    path:
      - ENERGY
      - Power
    dtype: float
    scale: 1.0
  smoothing:
    kind: exponential
    source_interval: 10

inverter:
  transport: deye_mqtt
  model: DeyeSunM160G4
  topic_prefix: deye

controllers:
  - type: reduce_consumption
    max_power: 600
    min_power: 80
    control_threshold_W: 50
    offset: -10.0
  - type: production_forecast

loop:
  update_interval: 60
