mqtt:
  host: localhost
  port: 1883
  username:
  password:

site:
  latitude: 0.0
  longitude: 0.0
  timezone: UTC

batteries: []

powermeter:
  type: mqtt_sensor
  topic: tele/powermeter/SENSOR
  filter:
    path:
      - ENERGY
      - Power
    dtype: float
    scale: 1.0

inverter:
  transport: deye_mqtt
  model: DeyeSunM160G4
  topic_prefix: deye

loop:
  update_interval: 60
